Projeto_Aulas/Projeto_Aulas/Areas/Admin/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.Context;
using App.Models;

namespace Projeto_Aulas.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ClienteController : Controller
    {
        private readonly AppDbContext _context;

        public ClienteController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Cliente
        public async Task<IActionResult> Index()
        {
              return _context.Clientes != null ? 
                          View(await _context.Clientes.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Cliente'  is null.");
        }

        // GET: Admin/Cliente/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ClienteID == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Admin/Cliente/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Cliente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClienteID,Nome,DataNascimento,Cep,Rua,Bairro,Cidade,Numero,Complemento,Senha")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Admin/Cliente/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Admin/Cliente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClienteID,Nome,DataNascimento,Cep,Rua,Bairro,Cidade,Numero,Complemento,Senha")] Cliente cliente)
        {
            if (id != cliente.ClienteID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ClienteID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Admin/Cliente/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ClienteID == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Admin/Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clientes == null)
            {
                return Problem("Entity set 'AppDbContext.Cliente'  is null.");
            }
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
          return (_context.Clientes?.Any(e => e.ClienteID == id)).GetValueOrDefault();
        }
    }
}

Projeto_Aulas/Projeto_Aulas/Areas/Admin/Controllers/FrontEndController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Projeto_Aulas.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FrontEndController : Controller
    {
        private readonly ILogger<FrontEndController> _logger;

        public FrontEndController(ILogger<FrontEndController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Camera()
        {
            return View();
        }
        public IActionResult Geolocalizacao()
        {
            return View();
        }
        public IActionResult BuscaCep()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Projeto_Aulas/Projeto_Aulas/Areas/Admin/Views/FrontEnd/BuscaCep.cshtml
@section scripts{
    <script src="~/js/CEP.js"></script>
}

Projeto_Aulas/Projeto_Aulas/Areas/Admin/Views/FrontEnd/Camera.cshtml
@section scripts{
    <script src="~/js/Camera.js"></script>
}


<style>
    .video{
        width: 400px;
        height: 200px;
        transform: scaleX(-1);
        transition: 500ms;
    }
    .foto{
        margin: 5px;
        cursor: pointer;
    }
    .foto:hover{
        transform: scale(1.2);
        transition: transform 0.2s;
    }

</style>

<h1 class="text-center">Captura de Câmera</h1>
<video class="video" autoplay></video>
<button class="btn btn-primary mx-auto d-block botaoCamera">Capturar</button>
<canvas class="canvas d-none" width="400" height="200"></canvas>
<div class="fotos d-flex flex-wrap"></div>

Projeto_Aulas/Projeto_Aulas/Areas/Admin/Views/FrontEnd/Geolocalizacao.cshtml
@section scripts{
    <script src="~/js/Geolocalizacao.js"></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
}

<h1>Geolocalização</h1>
<p>Latitude <span id="latitude"></span></p>
<p>Longitude <span id="longitude"></span></p>
<div id="map" style="height: 400px;"></div>

Projeto_Aulas/Projeto_Aulas/Areas/Admin/Views/FrontEnd/Index.cshtml
<h1>Aulas JS</h1>
<a class="nav-link" asp-area="Admin" asp-controller="FrontEnd" asp-action="Camera">Aula Câmera</a>
<a class="nav-link" asp-area="Admin" asp-controller="FrontEnd" asp-action="Geolocalizacao">Aula Geolocalização</a>
<a class="nav-link" asp-area="Admin" asp-controller="Cliente" asp-action="Index">Aula Busca-CEP</a>

<h1>Exercícios JS</h1>